### ISSUE TITLE
Refresh Readme.md to make it more newbie friendly

### ISSUE THREAD

**Issue by MrFaul** [ScreepsMods/screepsmod-mongo#15]
Please update your Readme.md with a clearer differentiation between Windows and Linux based operating systems.
It is quite confusing for novices.
I know it is annoying to make a step by step tutorial but far less than having them crying in the forum "doesn't work!!!".
A upload to the workshop would be good too.

**Comment by ags131** [comment]
The instructions are the same for both windows and linux, they also require that node, mongodb and redis should already be installed. 

I also will not be posting this mod in the workshop, installing it for the steam version of the server would cause more confusion when its installed but people haven't installed mongo and redis. 
If people want the mod, they can find it here or on npm and follow the README which has a clearly defined list of requirements.
