### ISSUE TITLE
Market broken

### ISSUE THREAD

**Issue by JestDotty** [ScreepsMods/screepsmod-mongo#4]
```
TypeError: Cannot create property 'price' on string '{'
    at _getOrders (E:\servers\screeps-server\node_modules\@screeps\engine\dist\game\market.js:27:53)
    at Object. (E:\servers\screeps-server\node_modules\@screeps\engine\dist\game\market.js:41:26)
    at Object.getAllOrders (evalmachine.:1:72)
```

on v: `"screepsmod-mongo": "^2.1.4"`

all data is new, and there are NPC terminal orders in the market already...

**Comment by ags131** [comment]
Is this with npm or docker container? that is all within the engine code and shouldn't be affected by screepsmod-mongo

**Comment by JestDotty** [comment]
Npm

Without mongodb it is not an issue (but then I have eperm db.json~ on
rewrites/randomly)

**Comment by ags131** [comment]
Hmm, windows or linux? NPC terminals? Is there orders returned from
`db['market.orders'].find()`?

**Comment by JestDotty** [comment]
windows 8.1

there are 4*5+2=22 npc terminals all on the outside of the map and a bunch of orders:

![image](https://user-images.githubusercontent.com/4729968/32704264-172ca356-c7d0-11e7-98f2-986983742239.png)

seems it doesn't know what db is?
```
E:\servers\screeps-server>npm run cli

> screeps-server@1.0.0 cli E:\servers\screeps-server
> screeps cli

Screeps CLI connected on localhost:21026.
-----------------------------------------
Screeps server v2.10.4 running on port 21025.
This CLI interface contains a virtual JavaScript machine which you can use to invoke internal server commands. Any valid JavaS
cript code is allowed. Type "help()" to learn more about commands.
> db['market.orders'].find()
ReferenceError: db is not defined
```

however, `storage.db['market.orders'].find` returns several:
![image](https://user-images.githubusercontent.com/4729968/32704299-b618e4f2-c7d0-11e7-83de-f8e2fc74fcfb.png)

**Comment by ags131** [comment]
Hmm, weird, I'll try to look into it on my side, it shouldn't ever be getting a string there, and screepsmod-mongo doesn't specifically touch market at all IIRC

**Comment by ags131** [comment]
It looks like there was a bug fixed in the screeps code back in september but it may not have been published to npm yet. https://github.com/screeps/engine/commit/f67f8ff784b7df305a193864e5f3811deef11e8c#diff-a1e6b02db4d5d95fc63d922c782c32bf

**Comment by JestDotty** [comment]
issue does not happen if screepsmod-mongo is removed from `mods.json`

however, applying the hotfix in the linked commit did fix it O-o

**Comment by ags131** [comment]
I'll have to poke at it some, i may be something done slightly different in the runtimeData population or something. I have posted an issue at https://github.com/screeps/engine/issues/69 to hopefully get updated in npm
