### ISSUE TITLE
Lokijs still used after install

### ISSUE THREAD

**Issue by kenanbit** [ScreepsMods/screepsmod-mongo#7]
On arch linux, with a freshly installed screeps server (`npm install -g screeps`), I followed these installation instructions carefully. I started the services for mongodb and redis. Upon running `npm install screepsmod-mongo`, mongo files were created under screeps/node_modules/screepsmod-mongo, screeps/node_modules/mongodb, and screeps/node_modules/mongodb-core. 

However, when I start the server cli, mongo is not defined, and lokijs still appears to be used for the storage module.

Am I missing something?

**Comment by ags131** [comment]
Check the logs to see if there was any errors, lokijs by default does still start, but screepsmod-mongo takes over before the modules connect.

**Comment by kenanbit** [comment]
There don't appear to be any errors in the logs. There are also no instances of `*mongo*` in the logs. Here is storage.log from the run:
```
Loading mods from "/usr/lib/node_modules/screeps/mods.json"
Starting storage server
Storage listening on 21027
[127.0.0.1:39712] Incoming connection
[127.0.0.1:39714] Incoming connection
[127.0.0.1:39716] Incoming connection
[127.0.0.1:39718] Incoming connection
[127.0.0.1:39720] Incoming connection
[127.0.0.1:39722] Incoming connection
[127.0.0.1:39724] Incoming connection
[127.0.0.1:39726] Incoming connection
```

Do I need to put something in the mods.json to make it use mongodb?

**Comment by ags131** [comment]
It looks like its trying to run screeps globally rather than in the local folder. I've seen quite a few issues related to installing globally. Best bet is to go into your local screeps folder, run `npm install screeps` (note the lack of `-g`), and use `npx screeps ...` for the command, if it still doesn't work, make sure `mods.json` has `node_modules/screepsmod-mongo/index.js`

**Comment by kenanbit** [comment]
I installed a fresh server without -g, as nonroot user in home directory. I then went did `install screepsmod-mongo` inside the screeps folder. There are still no errors in the logs when I run the server, and still no mongo object defined in the cli.

**Comment by kenanbit** [comment]
When I make sure `mods.json` has `node_modules/screepsmod-mongo/index.js`, it works (mongo is defined in the CLI). Perhaps that blurb should be in the setup instructions? Thanks for your help!

**Comment by ags131** [comment]
Their default setup is 'supposed' to setup a hook to auto-add it, in my experience, that rarely (if ever) works 
:(
Glad you got it working :)
